"use client"
import './globals.css'
import {  Poppins } from 'next/font/google'
import { Provider } from 'react-redux'
import store from '@/store/Index'


const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Provider store={store}>
      <body className={poppins.className}>
     
      <main>
        {children}
        </main>
       
      </body>
      </Provider>
    </html>
  )
}
